<?php

namespace Roowix\Test\Podkur;

use PHPUnit\Framework\TestCase;
use Roowix\Podkur\Api;
use Roowix\Podkur\DataBaseConnect;
use Roowix\Podkur\ResponseWriter;

class ApiTest extends TestCase
{
    private $uri;
    private $method;
    private $tableName;
    private $mockResponse;
    private $mockConnect;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->uri = 'localhost/api/1';
        $this->tableName = 'students';
        $this->mockResponse = $this->getMockBuilder(ResponseWriter::class)->disableOriginalConstructor()->getMock();
        $this->mockConnect = $this->getMockBuilder(DataBaseConnect::class)->disableOriginalConstructor()->getMock();
    }

    public function testResponseOfGetAction()
    {
        // arrange
        $this->method = 'GET';
        $this->mockConnect->method('takeAll')
            ->willReturn(["firstname" => 'test', "lastname" => 'test', "id" => 0]);
        $api = new Api($this->uri, $this->method, $this->tableName, $this->mockConnect, $this->mockResponse);

        // act
        $res = $api->run();

        // assert
        $this->assertNotEmpty($res);
        $this->assertEquals($res, '{"firstname":"test","lastname":"test","id":0}');
    }

    public function testResponseOfCreateAction()
    {
        // arrange
        $this->method = 'POST';
        $_POST = ["id" => 'test', "lastname" => 'test'];
        $this->mockConnect->method('insert')->willReturn(["firstname" => 'test', "lastname" => 'test', "id" => 0]);

        $api = new Api($this->uri, $this->method, $this->tableName, $this->mockConnect, $this->mockResponse);

        // act
        $res = $api->run();

        // assert
        $this->assertNotEmpty($res);
        $this->assertEquals($res, '{"firstname":"test","lastname":"test","id":0}');
    }

    public function testDeleteRunWithCorrectArgument()
    {
        // arrange
        $this->method = 'DELETE';
        $api = new Api($this->uri, $this->method, $this->tableName, $this->mockConnect, $this->mockResponse);

        $this->mockConnect->method('delete')->with(["id" => 1])->willReturn(["id" => 1]);

        // act
        $res = $api->run();

        // assert
        $this->assertEquals($res, '{"id":1}');
    }

    public function testRunUpdateAction()
    {
        // arrange
        $this->method = 'PUT';
        $_POST = ["firstName" => 'testName', "lastName" => 'testName', "id" => 1];
        $api = new Api($this->uri, $this->method, $this->tableName, $this->mockConnect, $this->mockResponse);

        $this->mockConnect->method('update')->with($_POST, ["id" => 1])->willReturn(["id" => 1]);

        // act
        $res = $api->run();

        // assert
        $this->assertNotEmpty($res);
    }

    public function testRunReturnNull()
    {
        // arrange
        //$this->method = '0';
        $api = new Api($this->uri, $this->method, $this->tableName, $this->mockConnect, $this->mockResponse);

        // act
        $res = $api->run();

        // assert
        $this->assertNull($res);
    }
}
